### ISSUE TITLE
BCC Perf samplers does not report correct counters

### ISSUE THREAD

**Issue by Skrinikov** [twitter/rezolus#143]
BPF perf counters do not return any counters at all.

There are few issues I want to address:
#### 1
Setting key = 0 does not expose the counter to user space. Not sure whether its a BPF constraint or a bug with rust-bcc.
```
BPF_HASH(counter, u32);
int do_perf_cnt(struct bpf_perf_event_data *ctx) {
   u32 key = 0;
   counter.increment(key); // <--- Does not work, need to have something else (pid works)
   return 0;
}
```

#### 2
Simply incrementing the sampler inside the bpf context is incorrect.
 Need to change `count.increment(key)` -> `count.increment(key, ctx->sample_period)`. See [llcstat](https://github.com/rust-bpf/rust-bcc/blob/master/examples/llcstat.c#L26)

#### 3
Sample frequency seems too low. We convert the sampling interval to hertz. By default 1000 milliseconds = 1Hz which seems a bit low as a sampling rate. (needs more investigation)

**Comment by brayniac** [comment]
Since we reverted #141 this is fixed, I've reopened #91
