### ISSUE TITLE
Basic usage documentation

### ISSUE THREAD

**Issue by skrzepto** [twitter/rezolus#15]
Brief usage documentation explaining on how to run rezolus. After running the binary I know I have to provide a config file but not sure how that is formatted.

```
        --config <FILE>    TOML config file
```

### Expected behavior

Documentation for usage to exist

### Actual behavior

Not that I could find from the readme file

### Steps to reproduce the behavior

Look at the readme

**Comment by brayniac** [comment]
@skrzepto - I'll add to the readme, but you can find an example config in the `configs` folder of this repository.

**Comment by brayniac** [comment]
@skrzepto - #16 should address this. Let me know if you have additional questions about usage.
