### ISSUE TITLE
Use from_ne_bytes methods to avoid the need to use unsafe

### ISSUE THREAD

**Issue by alex** [twitter/rezolus#2]
Example location:

https://github.com/twitter/rezolus/blob/2c1c61821a85916bef1a21d927e4ab83a1c788d7/src/samplers/ebpf/ext4/mod.rs#L133-L137

The `u32::from_ne_bytes` method can be used to avoid `unsafe`: https://doc.rust-lang.org/stable/std/primitive.u32.html#method.from_ne_bytes

**Comment by brayniac** [comment]
Thanks @alex - agree we can definitely change this at the various call sites.
