### ISSUE TITLE
Please tell me about the design concept

### ISSUE THREAD

**Issue by kash203** [twitter/rezolus#220]
I'm interested in this projects, I think that getting these values with low resources and high resolution is unique attraction.
But I cannot be sure of several points.
I'm understanding somehow with reading DESIGN.md > Metrics...
(I wasn't sure when I looked at the implementation with debugging... it is hard to read it because it it difficult for me.. I will take some times to read this.)

 **1. How to achieve oversampling**
The interval of Rezolus looks like higher rate with low resources than other products ,
But Rezolus looks like get the data by configured interval ,
How should I understand oversampling in the implementation?

(Does Oversampling mean simply "how to set interval" ?
And Rezolus can achieve it with high resolution with high sampling rate configured fine interval?

And is this indicate that for example, if the burst duration is 200ms, I should set the interval to 100ms ?)

**2. What does it mean "secondly rate"**
I cannot be sure this word but I believe this word is very important for understanding Rezolus concept.
I think first rate is configured interval in toml, and first rate value is recorded and displayed as metrics/histogram/count (case : cpu/frequency).
But actually, does secondly rate indicate simply metrics/histogram/percentile value?

**3. How to construct the histogram**
Is it constructed by the data that stored within time window?
For example, under window = 10s and interval = 100ms, Is percentile value decided by 100 samples?

**4. How to read the value (ex. cpu/frequency)**
There are cases that the server has several cpu. And rezolus looks like take each cpu's frequency.
But the result I can see from exposition (/vars etc..), it looks like only 1 specific cpu data (or summarized value).
If configuration is above setting and the server has 4 cpus, Is the sample stored 400 samples and the result indicate specific cpu's data?

**Comment by brayniac** [comment]
Hi @kash203 - these are some great questions! I'll try to get you some initial answers here and then try to get this into our docs.

1 - The oversampling is really just that we sample many times within a "window" https://github.com/twitter/rezolus/blob/master/configs/example.toml#L14 - for instance, we may sample on a secondly basis and collect every minute - this would get us 60 datapoints for calculating percentiles. If you are trying to capture things that are happening on even shorter timescales, you probably want to set the sampling "interval" to be even shorter - but you could potentially leave the "window" as minutely. With your example, yes, you probably do want to do 100ms or shorter intervals for the samplers which are likely to capture the relevant information. 

2 - An example to explain secondly rate is with some statistic that's sourced from a counter, not from a gauge or distribution. These sources are a key concept, and maybe the docs need to be improved to explain this better. In short, a counter is some metric like rx packets, which is monotonically increasing. If we were to store those instantaneous counter readings to produce percentiles, they would not be that useful. What we typically care about is the packet rate and bursts where we might be exceeding some threshold of packets/s. In Rezolus, we calculate a secondly rate from the change in counter value and the number of seconds between two consecutive readings. For packets, this would result in a metric that is packets/s (secondly rate). The rates between each consecutive pair of samples within the "window" are used to calculate a percentile value. For this example, we could see the p50 and p90 of packet rates within that minute. Again, if we're trying to capture very brief bursts, we need to sample at higher frequency (smaller interval).

3 - That's correct - however many samples occur within the window. So it would be ~100 samples for your example, but could be fewer if the sampler stalled for some reason or Rezolus was unable to keep up with the configured sampling rate. 

4 - cpu/frequency is admittedly a little weird, I think it's the one case where we're taking multiple gauges of things that are rates and trying to group them together. The main statistic is going to be from one particular core from the most recent sample. For this, the percentiles are much more useful - and yes, if you had 4 cpus, and 10s window with 100ms sampling, you'd have 400 samples to calculate a percentile.

Let me know if this explanation makes sense or if you have additional questions. I'll try to improve the docs accordingly.

**Comment by kash203** [comment]
Thanks @brayniac - san for your kind explanation and your answer is very helpful!

I mostly understand the concepts. 
There are no additional questions regarding this matter, but there are other points of concern, so I will raise them as an issue.

By the way, I think it is interesting that adding storing cpu's temperature for OC using coretemp (maybe only for Intel CPU) .
Rezolus already has stored frequency and cstate, so I think the metrics can be helpful for tuning.
