### ISSUE TITLE
build issue: v2.15.1 fails to build from release archive

### ISSUE THREAD

**Issue by mortymacs** [twitter/rezolus#277]
**Describe the bug**
Compiling the latest version is failing.

**To Reproduce**
1. Download https://github.com/twitter/rezolus/archive/refs/tags/v2.15.1.tar.gz
2. Extract it
3. $ cargo build --release

**Expected behavior**
Based on the document it should be compiled successfully.

**Screenshots**
```
   .....
   Compiling wrapcenum-derive v0.4.0
   Compiling thiserror v1.0.30
   Compiling rustcommon-histogram v1.0.0 (https://github.com/twitter/rustcommon?branch=master#88e07783)
   Compiling rustcommon-streamstats v0.1.0 (https://github.com/twitter/rustcommon?branch=master#88e07783)
   Compiling bcc v0.0.32
   Compiling rustcommon-heatmap v0.1.1 (https://github.com/twitter/rustcommon?branch=master#88e07783)
   Compiling nvml-wrapper v0.7.0
   Compiling rustcommon-metrics v2.0.0-alpha.0 (https://github.com/twitter/rustcommon?branch=master#88e07783)
   Compiling rezolus v2.15.1 (/home/mort/Downloads/rezolus-2.15.1)
error: failed to run custom build command for `rezolus v2.15.1 (/home/mort/Downloads/rezolus-2.15.1)`

Caused by:
  process didn't exit successfully: `/home/mort/Downloads/rezolus-2.15.1/target/release/build/rezolus-79176f2da258cf67/build-script-build` (exit status: 1)
  --- stderr
  Error: could not find repository from '/home/mort/Downloads/rezolus-2.15.1'; class=Repository (6); code=NotFound (-3)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Environment**
ArchLinux x86_64
Rustc 1.58.1 (Arch Linux rust 1:1.58.1-1)

**Additional context**
I'm not sure but probably it's related to the nightly build's note. I'm using the stable Rust version.

**Comment by brayniac** [comment]
That note about nightly is outdated and I need to remove that from the readme (#278 to track) . You can see from the [CI builds](https://github.com/twitter/rezolus/actions/workflows/cargo.yml?query=branch%3Amaster+event%3Apush) that builds have been passing and the [toolchain](https://github.com/twitter/rezolus/blob/master/rust-toolchain) is specified as stable. 

This appears to be a problem with how the releases are packaged, as the build script is depending on having the .git structure in-place for getting some additional version information. If you clone the repo and check-out the corresponding release tag it'll work for now (confirmed on Arch too). Changes will need to be made in the build process to account for how releases are packaged.

Thanks for filing this.

**Comment by brayniac** [comment]
@mortymacs - release cut for 2.15.2. Please re-open if you have any issues with the new release. Thanks again for opening this issue.

**Comment by mortymacs** [comment]
Awesome! Thank you! I just have prepared the AUR package https://aur.archlinux.org/packages/rezolus
