### ISSUE TITLE
build failure using latest rust nightly

### ISSUE THREAD

**Issue by lukasz-wolski** [twitter/rezolus#28]
Instructions indicate to build with rust nightly install, but project fails to build with:
rustc 1.39.0-nightly (9af17757b 2019-09-02).

May I ask to specify nightly rustc version used to produce binaries?

### Expected behavior

Build is producing binaries.
Instructions ammended with nightly version used by author.

### Actual behavior

Build fails for rustc 1.39.0-nightly (9af17757b 2019-09-02) with:
   Compiling x86 v0.19.0
     Running `CARGO_PKG_NAME=x86 CARGO_MANIFEST_DIR=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.19.0 CARGO_PKG_VERSION_MINOR=19 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION=0.19.0 CARGO_PKG_HOMEPAGE='https://github.com/gz/rust-x86' CARGO_PKG_REPOSITORY='https://github.com/gz/rust-x86' CARGO_PKG_AUTHORS='Gerd Zellweger <mail@gerdzellweger.com>:Eric Kidd <git@randomhacks.net>:Philipp Oppermann <dev@phil-opp.com>:Dan Schatzberg <schatzberg.dan@gmail.com>:John Ericson <John_Ericson@Yahoo.com>:Rex Lunae <rexlunae@gmail.com>:Brian Martin <bmartin@twitter.com>:Caleb Boylan <calebboylan@gmail.com>' LD_LIBRARY_PATH='/root/rezolus/target/debug/deps:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' CARGO_PKG_VERSION_PRE= CARGO_PKG_DESCRIPTION='Library to program x86 (amd64) hardware. Contains x86 specific data structure descriptions, data-tables, as well as convenience function to call assembly instructions typically not exposed in higher level languages.' OUT_DIR=/root/rezolus/target/debug/build/x86-b4cf20a8ca132655/out CARGO=/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_PKG_VERSION_MAJOR=0 rustc --edition=2018 --crate-name x86 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.19.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="csv"' --cfg 'feature="performance-counter"' --cfg 'feature="phf"' --cfg 'feature="phf_codegen"' --cfg 'feature="serde_json"' -C metadata=e495abe61bcdff7a -C extra-filename=-e495abe61bcdff7a --out-dir /root/rezolus/target/debug/deps -L dependency=/root/rezolus/target/debug/deps --extern bitflags=/root/rezolus/target/debug/deps/libbitflags-9d0eaefa633987ee.rmeta --extern phf=/root/rezolus/target/debug/deps/libphf-b29ef04220dcb0d2.rmeta --extern raw_cpuid=/root/rezolus/target/debug/deps/libraw_cpuid-93a645499f3040dd.rmeta --cap-lints warn`
error: Could not compile `x86`.

Caused by:
  process didn't exit successfully: `CARGO_PKG_NAME=x86 CARGO_MANIFEST_DIR=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.19.0 CARGO_PKG_VERSION_MINOR=19 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION=0.19.0 CARGO_PKG_HOMEPAGE='https://github.com/gz/rust-x86' CARGO_PKG_REPOSITORY='https://github.com/gz/rust-x86' CARGO_PKG_AUTHORS='Gerd Zellweger <mail@gerdzellweger.com>:Eric Kidd <git@randomhacks.net>:Philipp Oppermann <dev@phil-opp.com>:Dan Schatzberg <schatzberg.dan@gmail.com>:John Ericson <John_Ericson@Yahoo.com>:Rex Lunae <rexlunae@gmail.com>:Brian Martin <bmartin@twitter.com>:Caleb Boylan <calebboylan@gmail.com>' LD_LIBRARY_PATH='/root/rezolus/target/debug/deps:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' CARGO_PKG_VERSION_PRE= CARGO_PKG_DESCRIPTION='Library to program x86 (amd64) hardware. Contains x86 specific data structure descriptions, data-tables, as well as convenience function to call assembly instructions typically not exposed in higher level languages.' OUT_DIR=/root/rezolus/target/debug/build/x86-b4cf20a8ca132655/out CARGO=/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_PKG_VERSION_MAJOR=0 rustc --edition=2018 --crate-name x86 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.19.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="csv"' --cfg 'feature="performance-counter"' --cfg 'feature="phf"' --cfg 'feature="phf_codegen"' --cfg 'feature="serde_json"' -C metadata=e495abe61bcdff7a -C extra-filename=-e495abe61bcdff7a --out-dir /root/rezolus/target/debug/deps -L dependency=/root/rezolus/target/debug/deps --extern bitflags=/root/rezolus/target/debug/deps/libbitflags-9d0eaefa633987ee.rmeta --extern phf=/root/rezolus/target/debug/deps/libphf-b29ef04220dcb0d2.rmeta --extern raw_cpuid=/root/rezolus/target/debug/deps/libraw_cpuid-93a645499f3040dd.rmeta --cap-lints warn` (signal: 9, SIGKILL: kill)

### Steps to reproduce the behavior
Follow build instructions from README, i.e. invoke:
`cargo build -vv`

**Comment by brayniac** [comment]
It seems that you're having problems with the `x86` library building. Can you please clone that repo and see if that builds on its own? That you're getting a `SIGKILL` is a little strange. The upstream repo is https://github.com/gz/rust-x86

Here is a run in CI where Rezolus built on the same nightly you appear to have used in this case (2019-09-02) https://travis-ci.com/twitter/rezolus/jobs/230919812

**Comment by lukasz-wolski** [comment]
'rust-x86' does build fine on its own. Also building 'rust-x86' from .cargo subdir works fine (.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.19.0 in my case).
It looks like an issue with my env + cargo itself and therefore not rezolus specific.
IMHO issue can be closed.

**Comment by brayniac** [comment]
@lukasz-wolski thanks, closing this issue.
