### ISSUE TITLE
Extend usage documentation

### ISSUE THREAD

**Issue by kgrosvenor** [twitter/rezolus#88]
Documentation could do with more explanation, how do we send custom events?

**Comment by brayniac** [comment]
Hi @kgrosvenor - I'm unclear what you mean here. Rezolus does not receive custom events, but rather provides a way of gathering telemetry via samplers. To gather additional telemetry, one would need to write a sampler. The samplers can be found under https://github.com/twitter/rezolus/tree/master/src/samplers

Let me know if there's something I didn't understand about your question or if this answers it for you. Thanks!
