### ISSUE TITLE
x86 dependency seems to be unused

### ISSUE THREAD

**Issue by bjorn3** [twitter/rezolus#9]
If that is the only nightly requiring dependency, you may want to update the docs regarding requiring nightly, after removing the x86 dep.

**Comment by brayniac** [comment]
I believe you're correct that we can remove `x86` as a direct dependency. However, it is still a transient dependency via `perfcnt` which we are currently using for the performance counter telemetry. We may be able to eventually migrate the performance counters over to `bcc`. I'd rather move that to a separate issue, as we'll need to consider the implications in terms of taking on the dependency on the `bcc` even if we only want performance counters and do not intend to build with eBPF support. 

Leaving this one open to address removing the direct dependency on `x86`
